### ISSUE TITLE
yr not properly working if you change the xml url to another place.

### ISSUE THREAD

**Issue by skandix** [martinp/jarvis2#14]
# Appeared in Console When refreshing page
Job "yr (trigger: interval[0:05:00], next run at: 2016-02-01 08:38:59.568695)" raised an exception
 Traceback (most recent call last):
   File "/usr/local/lib/python2.7/dist-packages/apscheduler/scheduler.py", line 512, in _run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/negus/jarvis2/app/main.py", line 179, in _run_job
    body = job.get()
  File "/home/negus/jarvis2/app/jobs/yr.py", line 52, in get
    return self._parse(r.content)
  File "/home/negus/jarvis2/app/jobs/yr.py", line 44, in _parse
    'today': self._parse_tree(tree),
  File "/home/negus/jarvis2/app/jobs/yr.py", line 28, in _parse_tree
    windSpeed = data_root.xpath('windSpeed').pop()
IndexError: pop from empty list

#Debug Mode
--------------------------------------------------------------------------------
INFO in main [/home/negus/jarvis2/app/main.py:158]:
Scheduling job: [name=yr, interval=300, timeout=1, start_date=2016-02-01 08:33:59.568695]
--------------------------------------------------------------------------------

# /app/config.py #yr
JOBS['yr'] = {
   # Enable job
   'enabled': True,
   # Run job every N seconds
   'interval': 300,
   # URL for data
   'url': ('http://www.yr.no/sted/Norge/Aust-Agder/Grimstad/'
           'Grimstad/varsel.xml'),
    # Job timeout in seconds
    'timeout': 1
}

**Comment by martinp** [comment]
It fails because the weather station first in the list of weather stations doesn't report wind metrics for this particular location. It should be fixed on master.

**Comment by skandix** [comment]
awesome :+1:
